AllCops:
  Include:
    - Rakefile
    - config.ru
    - Gemfile
    - Capfile
    - db/seeds.rb
    - lib/**/*.rake
    - lib/**/*.cap
  Exclude:
    - config/*

Void:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  Max: 5

ClassLength:
  Max: 100
